"""Planner models and node — generates execution plans for multi-agent orchestration."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from langchain_core.messages import SystemMessage
from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from langchain_core.language_models import BaseChatModel
    from langchain_core.tools import BaseTool


class SubAgentTask(BaseModel):
    """A single sub-agent task within an execution plan.

    Attributes:
        id: Unique task identifier (e.g. "task_1").
        name: Human-readable name for the sub-agent.
        description: What the sub-agent should accomplish.
        instructions: Specific instructions for the sub-agent.
        required_tool_names: Names of tools this sub-agent needs.
        depends_on: Task IDs that must complete before this task.
    """

    id: str
    name: str
    description: str
    instructions: str
    required_tool_names: list[str] = Field(default_factory=list)
    depends_on: list[str] = Field(default_factory=list)


class ExecutionStep(BaseModel):
    """A group of tasks that can be executed in parallel.

    Attributes:
        step_number: Sequential step number.
        tasks: List of sub-agent tasks in this step.
    """

    step_number: int
    tasks: list[SubAgentTask]


class ExecutionPlan(BaseModel):
    """A structured execution plan generated by the planner.

    Attributes:
        goal: Summary of what the plan aims to accomplish.
        reasoning: Why this plan structure was chosen.
        steps: Ordered list of execution steps.
        estimated_complexity: Complexity estimate (simple/moderate/complex).
    """

    goal: str
    reasoning: str
    steps: list[ExecutionStep]
    estimated_complexity: str = "moderate"


PLANNER_SYSTEM_PROMPT = """You are a task planner. Analyze the user's request and create an ExecutionPlan.

Available tools:
{tool_descriptions}

Rules:
- Break complex tasks into independent sub-tasks
- Tasks without dependencies go in the same step (→ parallel execution)
- Tasks with dependencies go in later steps (→ sequential execution)
- Each sub-agent gets only the tools it needs
- Simple requests that don't need decomposition → 1 step, 1 task
- Use descriptive names for sub-agents
- Task IDs must be unique strings like "task_1", "task_2", etc.
- depends_on must reference valid task IDs from previous steps

{security_prompt}"""


async def generate_plan(
    llm: BaseChatModel,
    tools: list[BaseTool],
    messages: list[Any],
    *,
    security_prompt: str = "",
    max_iterations: int = 2,
) -> ExecutionPlan:
    """Generate an execution plan using the LLM with structured output.

    Args:
        llm: LangChain chat model instance.
        tools: Available tools for the plan.
        messages: User messages/history to plan for.
        security_prompt: Optional security prompt to inject.
        max_iterations: Maximum retry attempts for valid plan generation.

    Returns:
        A validated ExecutionPlan.

    Raises:
        ValueError: If the LLM fails to generate a valid plan after max_iterations.
    """
    tool_descriptions = "\n".join(f"- {t.name}: {t.description}" for t in tools)

    sec_section = f"\nSecurity constraints:\n{security_prompt}" if security_prompt else ""
    system_content = PLANNER_SYSTEM_PROMPT.format(
        tool_descriptions=tool_descriptions,
        security_prompt=sec_section,
    )

    structured_llm = llm.with_structured_output(ExecutionPlan)

    for attempt in range(max_iterations):
        try:
            plan = await structured_llm.ainvoke(
                [
                    SystemMessage(content=system_content),
                    *messages,
                ]
            )
            if plan and isinstance(plan, ExecutionPlan) and plan.steps:
                _validate_plan(plan, tools)
                return plan
        except Exception:
            if attempt == max_iterations - 1:
                raise

    msg = "Failed to generate a valid execution plan"
    raise ValueError(msg)


def _validate_plan(plan: ExecutionPlan, tools: list[BaseTool]) -> None:
    """Validate that the plan references only available tools and valid dependencies."""
    available_tool_names = {t.name for t in tools}
    all_task_ids: set[str] = set()

    for step in plan.steps:
        for task in step.tasks:
            for tool_name in task.required_tool_names:
                if tool_name not in available_tool_names:
                    msg = f"Plan references unknown tool: {tool_name}"
                    raise ValueError(msg)

            for dep_id in task.depends_on:
                if dep_id not in all_task_ids:
                    msg = f"Task {task.id} depends on unknown task: {dep_id}"
                    raise ValueError(msg)

            all_task_ids.add(task.id)
